#!/bin/bash
#
# This is a shortcut that aliases `git up [target="master"]` to:
#     1. Update local $TARGET branch with the remote
#     2. Rebase current branch from $TARGET, automatically stashing
#        and unstashing any unstaged changes

if [ -z "$1" ]; then
	TARGET="`git branch -l main master --format '%(refname:short)' | head -n1`"
else
	TARGET="$1"
fi

# Update the local branch with the remote. Assumes remote is "origin".
git fetch origin $TARGET:$TARGET

# Rebase against target branch, automatically stashing and unstashing
git rebase --rebase-merges --autostash "$TARGET"
