#!/bin/bash

#-- CONSTANTS
CONFIG_FILE=".phpcsrc"
EXIT_NOPHPCS=1

#-- Find real path to me
ME="`readlink $0`"
if [ -z "$ME" ]; then
  ME="$0"
fi


#-- Find the first real phpcs in our $PATH
BINS="`which -a phpcs`"
for f in $BINS; do
  if [ "$ME" != "$f" ]; then
    PHPCS_BIN="$f";
    break;
  fi
done
if [ -z "${PHPCS_BIN}" ]; then
  exit $EXIT_NOPHPCS
fi

ORIG_DIR="$PWD"
#-- Find a .phpcsrc file in the parent directory
if [ -f "${CONFIG_FILE}" ]; then
  source "${CONFIG_FILE}"
else
  while [ -n "${PWD##*/}" ]; do
    if [ -f "${CONFIG_FILE}" ]; then
      source "${CONFIG_FILE}"
      break;
    fi
    cd ..
  done
fi
cd "${ORIG_DIR}"

CMD="$PHPCS_BIN"
if [ -n "${PHPCS_STANDARD}" ]; then
  CMD="$CMD --standard=${PHPCS_STANDARD}"
fi

$CMD $@
